name: Node CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Backend
      - name: Install Backend dependencies
        run: npm install
        working-directory: backend

      - name: Lint Backend
        run: npm run lint || echo "No lint script"
        working-directory: backend

      - name: Test Backend
        run: npm test || echo "No test script"
        working-directory: backend

      # Frontend
      - name: Install Frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Lint Frontend
        run: npm run lint || echo "No lint script"
        working-directory: frontend

      - name: Test Frontend
        run: npm test || echo "No test script"
        working-directory: frontend
